export default {
    logo: require('../assets/logo.png'),
    logPolygonTop: require('../assets/login-polygon-top.png'),
    //logSchoolImage: require('../assets/login-school-img.png'),
    logSquare: require('../assets/login-square.png'),
    logCircle: require('../assets/login-circle.png'),
    logPolygonBottom: require('../assets/login-polygon-bottom.png'),
    forgetPassword: require('../assets/forget-password.png'),
    headerBackground: require('../assets/background.png'),
    avatar: require('../assets/avatar.png'),
    backgroundImageApp: require('../assets/back-app.jpg'),
    sleepNatimeImage: require('../assets/sleeping.png'),
    howIateImage: require('../assets/how-ate.png'),
    photoMenu: require('../assets/menu_photo.jpg'),
    languageFr: require('../assets/fr.png'),
    languageEn: require('../assets/en.png'),
    noBookImage: require('../assets/menu_photo.jpg'),
    logoHeader: require('../assets/logo_small.png'),
};
