export default {
    LOGIN: '/',
    FORGOT_PASSWORD: '/password-forget',


    TAB_HOME: 'index',
    TAB_EVAL: 'eval',
    TAB_TUITION: 'tuition',
    TAB_CALENDAR: 'edt/index',
    TAB_MORE: 'more',
    //TAB_MORE: 'more/index',

    TAB_HEAD_TUITION_PAYMENT: 'TAB_HEAD_TUITION_PAYMENT',
    TAB_HEAD_TUITION_DEADLINE: 'TAB_HEAD_TUITION_DEADLINE',


    DRAWER: 'Drawer',
    DRAWER_HOME: 'DRAWER_HOME',
    DRAWER_PROFILE: 'DRAWER_PROFILE',
    DRAWER_SETTINGS: 'DRAWER_SETTINGS',
    DRAWER_CONTRACT: 'DRAWER_CONTRACT',
    CONTRACT_STACK: 'CONTRACT_STACK',
    CONTRACT_SCREEN: 'CONTRACT_SCREEN',
    MORE_MENU: 'MORE_MENU',
    ABSENCE_SCREEN: 'ABSENCE_SCREEN',
    AVERAGE_SCREEN: 'AVERAGE_SCREEN',
    BULLETIN_SCREEN: 'BULLETIN_SCREEN',
    TEACHERS_SCREEN: 'TEACHERS_SCREEN',
};
